// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Coupon
{
    public int Id { get; set; }

    public string Productname { get; set; }

    public string Description { get; set; }

    public int? Amount { get; set; }
}